services: 
  mysqlDB:
    image: mysql:8 
    container_name: mysql_db
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./datas/:/var/lib/mysql-files/
    environment:
      - MYSQL_DATABASE=MYSQL
      - MYSQL_ROOT_PASSWORD=MYSQL
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  mysql-volume:
    driver: local