use datas;

SELECT 
    *,
    SUM(VL_SALDO_INICIAL - VL_SALDO_FINAL) AS Total_Despesas
FROM 
    demonstracoesContabeis
WHERE 
    DESCRICAO = "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR "
    AND TRIMESTRE in ("4T2024", "3T2024", "2T2024","1T2024")
GROUP BY 
    DATA,
    REG_ANS,
    CD_CONTA_CONTABIL,
    DESCRICAO,
    VL_SALDO_INICIAL,
    VL_SALDO_FINAL,
    TRIMESTRE
ORDER BY 
    Total_Despesas DESC
LIMIT 10;